---
- hosts: jenkins
  become_user: root
  become: true
  tasks:
  
    - name: Download Repo file
      ansible.builtin.get_url: 
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    
    - name: Download and install key
      ansible.builtin.rpm_key: 
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key 

    - name: Install java
      dnf:
       name:
       - java-17-openjdk
    
    - name: Install jenkins 
      dnf:
       name:
       - jenkins
       state: present

    - name: Install git
      dnf:
       name:
       - git
       state: present

     - name: Disable firewalld
       ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: False

    - name: Start service
      ansible.builtin.service:
       name: jenkins 
       state: started

    - name: Make sure jenkins service unit is running
      ansible.builtin.systemd:
       state: started
       name: jenkins

    - name: Install configuration-as-code plugin 
      jenkins_plugin:
      name: "{{ item }}"
       url_username: admin
       url_password: "{{jenkins_password.stdout}}"
       url: http://localhost:8080
      loop:
      - configuration-as-code
      - sonar
      - github-plugin
      - job-dsl-plugin